# src/main/resources/application.yml (for Eureka Server)
spring:
  application:
    name: amazon-server # Name of your Eureka Server application
eureka:
  client:
    # A Eureka server typically does not register itself with another Eureka server
    # nor does it need to fetch the registry from another server.
    register-with-eureka: false
    fetch-registry: false
#  server:
    # Optional: If you want to disable self-preservation mode (not recommended for production)
    # enable-self-preservation: false
    # Optional: How often the server purges instances that are not renewed (in milliseconds)
    # eviction-interval-timer-in-ms: 10000
server:
  port: 8761 # The port on which your Eureka server will run